name: Validate

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
        - main
        - develop
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "plugin"
